---
ci:
  # format compatible with commitlint
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autoupdate_schedule: monthly
  autofix_commit_msg: |
    chore: auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  skip:
    # https://github.com/pre-commit-ci/issues/issues/55
    - pip-compile
default_language_version:
  # Needed in order to make pip-compile output predictable.
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    # keep it before yamllint
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: >
          (?x)^(
            examples/playbooks/(with-skip-tag-id|unicode).yml|
            examples/playbooks/example.yml
          )$
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
        language_version: python3
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint --strict
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          # https://github.com/pre-commit/mirrors-isort/issues/9#issuecomment-624404082
          - --filter-files
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8.git
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-2020>=1.6.0
          - flake8-docstrings>=1.5.0
          - flake8-pytest-style>=1.2.2
          - flake8-rst-docstrings>=0.2.3
          - flake8-rst>=0.8.0
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        # empty args needed in order to match mypy cli behavior
        args: ["--strict"]
        additional_dependencies:
          - pytest
  - repo: https://github.com/pycqa/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        additional_dependencies:
          - pytest
  # Keep last due to being considerably slower than the others:
  - repo: local
    hooks:
      - id: pip-compile-upgrade
        # To run it execute: `pre-commit run pip-compile-upgrade --hook-stage manual`
        name: Upgrade constraints files and requirements
        files: ^(setup\.py|setup\.cfg|requirements\.txt)$
        language: python
        entry: python -m piptools compile --upgrade -q --strip-extras --extra test --output-file=requirements.txt setup.cfg
        pass_filenames: false
        stages:
          - manual
        additional_dependencies:
          - pip-tools>=6.8.0
      - id: pip-compile
        name: Check constraints files and requirements
        files: ^(setup\.py|setup\.cfg|requirements\.txt)$
        language: python
        entry: python -m piptools compile -q --strip-extras --extra test --output-file=requirements.txt setup.cfg
        pass_filenames: false
        additional_dependencies:
          - pip-tools>=6.8.0
